<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>BetterHI3Launcher</RootNamespace>

    <!-- Assembly Information -->
    <ApplicationIcon>Assets\Images\Icon.ico</ApplicationIcon>
    <AssemblyTitle>Better HI3 Launcher</AssemblyTitle>
    <ProductName>Better HI3 Launcher</ProductName>
    <Company>Bp</Company>
    <Authors>$(Company)</Authors>
    <Version>1.6</Version>
    <ProductVersion>$(Version)</ProductVersion>
    <Copyright>Copyright (c) $(Company), under The "Unlicense" License</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageReference Include="AssetsTools.NET" Version="2.0.12" />
    <PackageReference Include="ini-parser" Version="3.4.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.9" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="Squid-Box.SevenZipSharp" Version="1.6.2.24" />
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.9" />
    <PackageReference Include="System.Globalization.Calendars" Version="4.3.0" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.9" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="10.0.9" />
    <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
    <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Xaml">
      <RequiredTargetFramework>4.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="UIAutomationProvider" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>

  <!-- Exclude unnecessary files from Hi3Helper.* submodules -->
  <ItemGroup>
    <None Remove="Hi3Helper.*\**" />
    <Compile Remove="Hi3Helper.*\**" />
    <EmbeddedResource Remove="Hi3Helper.*\**" />
  </ItemGroup>

  <!-- Embedded Files (including ones from Fody) -->
  <ItemGroup>
    <EmbeddedResource Include="costura-win-x64\7zxa.dll" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\**" />
    <Resource Include="Assets\Images\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Hi3Helper.Http\Hi3Helper.Http.Universal.csproj" />
    <ProjectReference Include="Hi3Helper.Sophon\Hi3Helper.Sophon.Universal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>